auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
kramdown:
  coderay_css: class
exclude: [shower,themes]

default_theme: ribbon
default_lang: en
default_body_class: list

author:
    name: Audrey Tang
    company:
        name: NTHU 2013
        # url:  http://example.com/

fork_url: https://github.com/audreyt/moedict-webkit
progress: true
